Module: ML Infra Projects
caetano-colin/terraform-google-enterprise-genai pull request #5
Opened 2024-05-09 11:53 UTC by caetano-colin

2024-05-13 18:24 UTC, caetano-colin commented on 4-projects/modules/ml_single_project/remote.tf
> +  environment_kms_project_id = try(data.terraform_remote_state.environments_env.outputs.env_kms_project_id, "")
virar parâmetro

2024-05-14 19:16 UTC, daniel-cit commented
Check the output for diffs and correct using terraform fmt <dir>

2024-05-14 19:30 UTC, caetano-colin commented
> Check the output for diffs and correct using terraform fmt

What do you mean by "diffs"?

About terraform fmt:

I opened a PR to fix the build error:
https://github.com/GoogleCloudPlatform/terraform-google-enterprise-genai/pull/39

When merging these changes to this branch, build is green:
https://github.com/caetano-colin/terraform-google-enterprise-genai/pull/5/commits/be0ba50b372727917e4f98586d169353622a1cae

I reverted the change above on this PR to keep the scope closed, as you can see in commit 
https://github.com/caetano-colin/terraform-google-enterprise-genai/pull/5/commits/38069e26fd9fc380469dd86301fb935b3bb9555f

2024-05-14 19:34 UTC, daniel-cit requested changes
some minor fixes

2024-05-14 19:34 UTC, daniel-cit commented on 4-projects/modules/ml_single_project/README.md
> +<!-- BEGINNING OF PRE-COMMIT-TERRAFORM DOCS HOOK -->
Please add a `#` with the full name of module and a paragraph with a brief explanation

2024-05-14 19:34 UTC, daniel-cit commented on 4-projects/modules/ml_single_project/main.tf
> +  name                     = "${var.project_prefix}-${local.env_code}-${var.business_code}${var.project_suffix}"
this could be a variable

2024-05-14 19:34 UTC, daniel-cit commented on 4-projects/modules/ml_single_project/main.tf
> +    prevent_destroy = false
this could be a variable

2024-05-14 19:34 UTC, daniel-cit commented on 4-projects/modules/ml_single_project/outputs.tf
> +  description = "Project sample project id."
```suggestion
  description = "Project ID."
```

2024-05-14 19:34 UTC, daniel-cit commented on 4-projects/modules/ml_single_project/outputs.tf
> +  description = "Project sample project number."
```suggestion
  description = "Project number."
```

2024-05-14 19:34 UTC, daniel-cit commented on 4-projects/modules/ml_single_project/outputs.tf
> +  value       = distinct(concat(var.activate_apis, ["billingbudgets.googleapis.com"]))
this value should be in a local to be used in both places this is used

2024-05-14 19:34 UTC, daniel-cit commented on 4-projects/modules/ml_single_project/outputs.tf
> +  description = "Name of the Project."
```suggestion
  description = "Project Name."
```

2024-05-14 19:34 UTC, daniel-cit commented on 4-projects/modules/ml_single_project/variables.tf
> +  description = "The organization id for the associated services"
```suggestion
  description = "The Organization ID"
```

2024-05-14 19:34 UTC, daniel-cit commented on 4-projects/modules/ml_single_project/variables.tf
> +  description = "The environment the single project belongs to"
```suggestion
  description = "The environment the project belongs to"
```

2024-05-14 19:34 UTC, daniel-cit commented on 4-projects/modules/ml_single_project/variables.tf
> +  description = "The type of VPC to attach the project to. Possible options are base or restricted."
```suggestion
  description = "The type of VPC to attach the project to. Possible options are `base` or `restricted`."
```

2024-05-14 19:34 UTC, daniel-cit commented on 4-projects/modules/ml_single_project/variables.tf
> +  description = "The type of VPC to attach the project to. Possible options are base or restricted."
description needs to say what happens if the value is `""`

2024-05-14 19:34 UTC, daniel-cit commented on 4-projects/modules/ml_single_project/variables.tf
> +  description = "Project default service account setting: can be one of `delete`, `depriviledge`, or `keep`."
description need to be updated with the current possible values. the default value is not one of the options listed

2024-05-14 19:34 UTC, daniel-cit commented on 4-projects/modules/ml_infra_projects/outputs.tf
> +  description = "Service Catalog Project ID."
for this description and all descriptions, both in variables and outputs, a decision must be made if the description will end with a `.` or not.

2024-05-14 19:34 UTC, daniel-cit commented on 4-projects/modules/ml_infra_projects/variables.tf
> +  description = "The organization id for the associated services"
```suggestion
  description = "The Organization ID"
```

2024-05-14 19:34 UTC, daniel-cit commented on 4-projects/modules/ml_infra_projects/variables.tf
> +  description = "The type of VPC to attach the project to. Possible options are base or restricted."
```suggestion
  description = "The type of VPC to attach the project to. Possible options are `base` or `restricted`."
```
description needs to say what happens if the value is ""

2024-05-14 19:34 UTC, daniel-cit commented on 4-projects/modules/ml_infra_projects/variables.tf
> +  description = "Project default service account setting: can be one of `delete`, `depriviledge`, or `keep`."
description need to be updated with the current possible values. the default value is not one of the options listed

2024-05-14 19:38 UTC, daniel-cit commented on 4-projects/modules/ml_infra_projects/variables.tf
> +  default     = "abcd"
This is not the default value in the foundation
https://github.com/terraform-google-modules/terraform-example-foundation/blob/master/4-projects/modules/single_project/variables.tf#L61

2024-07-22 10:48 UTC, closed without merging